### ISSUE TITLE
Move to R5 (discussion)

### ISSUE THREAD

**Issue by joofio** [hl7-eu/unicom-ig#85] opened 2023-01-06 10:01 UTC
For the time being lets compile the reasons for upgrading to the R5 in a point in the future:

1. 
2.

**Comment by rlindstrm** [comment] 2023-01-06 17:06
1. Because redoing everything on a regular basis is fun, and repetition is the mother of all learning.

**Comment by costateixeira** [comment] 2023-01-06 17:14
For the time being lets compile the reasons for upgrading to the R5 in a point in the future:

1. + R4B has some breaking issues that require us to do workarounds and for which a release is not expected soon (if ever)
2. + HAPI does not support inline validation on R4B
3. + Alignment with e.g. Gravitate project
4. + There's not much rework involved when moving resources and scripts to R5
5. - There is some rework in the tooling (visualizer, scripts, etc)

**Comment by rlindstrm** [comment] 2023-01-07 09:33
> 1. (+) R4B has some breaking issues that require us to do workarounds and for which a release is not expected soon (if ever)

For value set binding errors we can do workarounds, but the fact that it does not allow one product to have two administration routes, is breaking the data and there is no fix. We can bend the profiles but not the data.
So I would put two pluses here. :)

6. (-) R5 is still not stable and will keep changing. That was the reason we chose R4B, so I guess it would be fair to mention it with a minus.

**Comment by simodiaco** [comment] 2023-01-09 10:38
@costateixeira 
> (+) R4B has some breaking issues that require us to do workarounds and for which a release is not expected soon (if ever)

Can you be more specific? What kind of issues? 

> (+) HAPI does not support inline validation on R4B

We can use the FHIR validator until R5 final gets released or HAPI FHIR adds full support validation for R4B

> (+) Alignment with e.g. Gravitate project

The Unicom project should not depend on other projects. I don't think that's a good reason to use any pre-release version. Besides, since Unicom is in a more advanced stage, should be Gravitate to conform to Unicom.

> (+) There's not much rework involved when moving resources and scripts to R5

(+R4B) If we keep going with R4B, we don't need to do any rework at all. 

@rlindstrm 
> For value set binding errors we can do workarounds, but the fact that it does not allow one product to have two administration routes, is breaking the data and there is no fix. We can bend the profiles but not the data.
So I would put two pluses here. :)

I took a look at the [MedicinalProductDefinition](http://hl7.org/fhir/medicinalproductdefinition.html) and I see that cardinality for route is 0..* so I don't understand the issue. Anyway, we could use [Extention](http://hl7.org/fhir/extensibility.html) in order to add as many routes as we like.


7. (-) Is difficult estimate DW's effort for mantaining the T6.1 if we work with pre-realeses version of R5. Could be very expensive: every time that a new versione of R5 is released, we will have to change potentially a big amount of code.
8. (-) We depend on third party's libraries (HAPI). Every time a new pre-realease version of R5 gets released, we need to wait until HAPI implements the new specification. In that time-frame, we won't able to upgrade to the latest version and at the same time our server will not be supported by tools.

No solution will ever be perfect, we need to stick to the one that is more cost-effective and predictable. We strongly advise that we keep working with R4B until R5-final is done.

**Comment by rlindstrm** [comment] 2023-01-09 10:58
> @rlindstrm
> 
> > For value set binding errors we can do workarounds, but the fact that it does not allow one product to have two administration routes, is breaking the data and there is no fix. We can bend the profiles but not the data.
> > So I would put two pluses here. :)
> 
> I took a look at the [MedicinalProductDefinition](http://hl7.org/fhir/medicinalproductdefinition.html) and I see that cardinality for route is 0..* so I don't understand the issue. Anyway, we could use [Extention](http://hl7.org/fhir/extensibility.html) in order to add as many routes as we like.

The problem is explained in the issue #80 (number 2), and it has made its way to HL7 Jira [ticket](https://jira.hl7.org/browse/FHIR-39755). It will be fixed for R5, but not sure if for R4B. There is hope I think.

The other, less breaking issue is that value sets that are used in the core FHIR spec sometimes don't resolve and that gives qa errors in the IG. It has been fixed for R5, but not too much hope for R4B. We have nearly got rid of them by creating dummy value set bindings in profiles (issue #84).

DataWizard's FHIR API currently uses R5, so even if we stay at R4B, you would need to do some rework. 

Personally, I have no preference.

**Comment by rlindstrm** [comment] 2023-01-18 22:07
I guess moving to R5 is the only way to get the qa clean, so can we start an issue for moving a branch to R5 to try it out?

**Comment by rlindstrm** [comment] 2023-01-24 17:24
Decision from 24.01 meeting: we will NOT move the main branch to R5 before technical review (1st of Feb). Currently everything is set up in R4B, and we don't want to encounter unexpected issues.

**Comment by rlindstrm** [comment] 2023-01-31 08:26
mpd-r5 branch is now functional R5. 
To help building, EMA ATC is reduced into what we actually use. 
There are still changes in template-work branch that are not in R5 (templates themselves, and also some data fixes).

**Comment by rlindstrm** [comment] 2023-02-03 19:18
Closing this one - too late to discuss now. :)

**Closed by rlindstrm** 2023-02-03 19:18 UTC
