### ISSUE TITLE
Substances value set

### ISSUE THREAD

**Issue by rlindstrm** [hl7-eu/unicom-ig#62] opened 2022-12-02 18:56 UTC
I hope I remember correctly what we agreed on. Please correct if needed:
- Create substances **code system** based on EMA SPOR SMS codes (we did not discuss this part, I just think it's easier to align with full eHDSI Substances value set, but you can argue)
- Create substances **value set** from values provided by Robert (subset of SMS)
- Remember that Robert's file contains extra attributes and mappings to other code systems which may be used later to enhance whatever we're trying to achieve. 
- EMA is waiting for the feedback for how to improve SMS and which data is necessary for third parties to access. Let's document that along the way.

   

Some info in https://github.com/hl7-eu/unicom-ig/issues/32#issuecomment-1316724487_

**Comment by Censacrof** [comment] 2022-12-05 08:53
Hi @rlindstrm , if I remember correctly, we agreed to first create a valuesets for all SMS Substances, and then we will create a valueset for Substances With The Role of PAI (Precise Active Ingredient), but only if we need it.

Also, isn't this a duplicate of #32 ?

**Comment by rlindstrm** [comment] 2022-12-05 10:23
I understood we wanted to close #32 because it is kind of endless. That's why I created new smaller issues. Feel free to close or reorganise, I'm no good at this management. 
We can start from all SMS substances code system/ value set. 
If needed, we can create a subset value set to just provide PPL substances (PAI or not).

I don't think we need a separate value set for PAI. But time will tell.

**Comment by Censacrof** [comment] 2022-12-05 10:25
Haha, no worries. I think we can close this issue. BTW, I just finished creating all ValueSets for UCUM, EDQM and SMS, so we will be able to close #32 as well soon.

**Closed by Censacrof** 2022-12-05 10:25 UTC
